name: Sanitary End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: window 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5

        with:
            Command: npm run test2:SearchProduct

      -name: Cypress test report
      if: always()
      - uses: actions/upload-artifact@v3
        with:
        name: Mochawesome Test Report
        path: cypress/reports/html/index.html 

      -name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
      env:
        
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Cypress Automation report https://github.com/hasham1234/cypressAutomation/actions/new'
        SLACK_TITLE: Cypress Web test
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

         
         